CREATE TABLE schema_migrations (version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE accounts (
    id text PRIMARY KEY,
    handle text NOT NULL UNIQUE CHECK (handle ~ '^[a-z0-9_]{3,24}$'),
    password_hash text NOT NULL,
    recovery_hash text NOT NULL,
    display_name text NOT NULL CHECK (char_length(display_name) BETWEEN 1 AND 80),
    bio text NOT NULL DEFAULT '' CHECK (char_length(bio) <= 500),
    usage_sharing_enabled integer NOT NULL DEFAULT 0 CHECK (usage_sharing_enabled IN (0,1)),
    created_at text NOT NULL
);
CREATE TABLE sessions (
    token_hash text PRIMARY KEY,
    sequence bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id text NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    created_at bigint NOT NULL,
    expires_at bigint NOT NULL
);
CREATE INDEX sessions_account ON sessions(account_id);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE usage_events (
    sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id text NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    event_id text NOT NULL,
    payload text NOT NULL CHECK (octet_length(payload) <= 8192),
    timestamp text NOT NULL,
    input_tokens integer CHECK (input_tokens BETWEEN 0 AND 1000000000),
    output_tokens integer CHECK (output_tokens BETWEEN 0 AND 1000000000),
    cached_input_tokens integer CHECK (cached_input_tokens BETWEEN 0 AND 1000000000),
    reasoning_output_tokens integer CHECK (reasoning_output_tokens BETWEEN 0 AND 1000000000),
    UNIQUE(account_id,event_id)
);
CREATE INDEX usage_account_sequence ON usage_events(account_id,sequence DESC);
CREATE TABLE rate_limits (
    key text PRIMARY KEY,
    window_start bigint NOT NULL,
    hits integer NOT NULL,
    expires_at bigint NOT NULL
);
CREATE INDEX rate_expiry ON rate_limits(expires_at);
INSERT INTO schema_migrations(version) VALUES (1);
